[project]
name = "frappe-mcp"
version = "0.1.0"
description = "Frappe MCP allows running a Frappe app as an MCP server"
authors = [{ name = "Alan Tom", email = "me@18alan.space" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["Werkzeug==3.1.3", "pydantic (>=2.11.7,<3.0.0)"]
